# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.parent.example.com:
  peer1.parent.example.com:
  peer0.child.example.com:
  peer1.child.example.com:

networks:
  reward_blockchain:

services:

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - reward_blockchain

  ca0:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-parent
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.parent.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/fe894c31d9d01a1b6c2a70e894b85b97efe1a0c485ab19f3ca83bdf16a4b9296_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.parent.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/fe894c31d9d01a1b6c2a70e894b85b97efe1a0c485ab19f3ca83bdf16a4b9296_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/parent.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerparent
    networks:
      - reward_blockchain

  ca1:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-child
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.child.example.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b9dc9e6fb1ba6b0ec07de0065300278ab9fb15cb06e2f306e0af9c07d8a5d6a4_sk
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.child.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b9dc9e6fb1ba6b0ec07de0065300278ab9fb15cb06e2f306e0af9c07d8a5d6a4_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/child.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerchild
    networks:
      - reward_blockchain


  peer0.parent.example.com:
    container_name: peer0.parent.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.parent.example.com
    depends_on:
      - orderer.example.com
    networks:
      - reward_blockchain

  peer1.parent.example.com:
    container_name: peer1.parent.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.parent.example.com
    depends_on:
      - orderer.example.com
    networks:
      - reward_blockchain

  peer0.child.example.com:
    container_name: peer0.child.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.child.example.com
    depends_on:
      - orderer.example.com
    networks:
      - reward_blockchain

  peer1.child.example.com:
    container_name: peer1.child.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.child.example.com
    depends_on:
      - orderer.example.com
    networks:
      - reward_blockchain


  cli:
    container_name: cli
    image: hyperledger/fabric-tools
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.parent.example.com:7051
      - CORE_PEER_LOCALMSPID=parent
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/parent.example.com/peers/peer0.parent.example.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/parent.example.com/peers/peer0.parent.example.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/parent.example.com/peers/peer0.parent.example.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/parent.example.com/users/Admin@parent.example.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.example.com
      - peer0.parent.example.com
      - peer1.parent.example.com
      - peer0.child.example.com
      - peer1.child.example.com
      - ca0
      - ca1
    networks:
      - reward_blockchain
